### ISSUE TITLE
Update default `http_ssl_version`

### ISSUE THREAD

**Issue by eafif** [wildbit/postmark-gem#86]
Getting the following error with the latest version of openssl on Ubuntu 20.04:
`OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: no protocols available`

```
apt-cache policy openssl
openssl:
  Installed: 1.1.1f-1ubuntu2
  Candidate: 1.1.1f-1ubuntu2
```

I can get it to work by using `Postmark::ApiClient.new(api_token, {http_ssl_version: :TLSv1_2})`.

Calling `openssl s_client -connect api.postmarkapp.com:443` shows that the certificate uses `TLSv1.2`:

```
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
```
